// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdapterId = "yt_dlp_v1" | "streamlink_v1" | "n_m3u8_dl_re_v1" | "gallery_dl_v1" | "ffmpeg_v1" | "aria2_v1" | "curl_worker_v2";
