// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppInfo = { version: string, portable: boolean, payloadPath: string, statePath: string, dataPath: string, enginesPath: string, updatesPath: string, maxParallelJobs: number, };
