// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreUpdateStatus = { transactionId: string, state: string, targetName: string, version: string, securitySequence: number, diagnostic: string | null, updatedAt: string, };
