// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineErrorKind = "unsupported" | "extractor_broken" | "protocol_unsupported" | "transient" | "auth_required" | "forbidden" | "geo_restricted" | "rate_limited" | "protected_media" | "integrity" | "disk" | "tls" | "host_key" | "canceled" | "internal";
