// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId.js";
import type { EngineCapability } from "./EngineCapability.js";

export type EngineDescriptor = { id: string, version: string, adapter_id: AdapterId, adapter_api: number, entrypoint: string, companions: { [key in string]: string }, capabilities: Array<EngineCapability>, };
