// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineCapability = "site_extraction" | "live_plugin" | "gallery_extraction" | "hls" | "dash" | "mss" | "direct_http" | "ftp" | "sftp" | "metalink" | "post_processing";
