// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FormatOption = { id: string, label: string, container: string | null, estimated_bytes: number | null, };
