// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InputSource = { "type": "url", value: string, } | { "type": "local_manifest", path: string, } | { "type": "local_metalink", path: string, };
