// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiError } from "./ApiError.js";
import type { JobId } from "./JobId.js";
import type { JobState } from "./JobState.js";

export type JobEvent = { "type": "state_changed", id: JobId, state: JobState, } | { "type": "progress", id: JobId, downloaded_bytes: number, total_bytes: number | null, speed_bytes_per_second: number | null, } | { "type": "failed", id: JobId, error: ApiError, } | { "type": "removed", id: JobId, };
