// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobState = "probing" | "awaiting_selection" | "queued" | "preparing" | "downloading" | "post_processing" | "paused" | "interrupted" | "completed" | "failed" | "canceled";
