// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiError } from "./ApiError.js";
import type { JobId } from "./JobId.js";
import type { JobSpec } from "./JobSpec.js";
import type { JobState } from "./JobState.js";
import type { ResolvedPlan } from "./ResolvedPlan.js";

export type JobSnapshot = { id: JobId, spec: JobSpec, state: JobState, plan: ResolvedPlan | null, progress: number, downloaded_bytes: number, total_bytes: number | null, speed_bytes_per_second: number | null, error: ApiError | null, created_at: string, updated_at: string, engine_versions: { [key in string]: string }, };
