// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSource } from "./InputSource.js";
import type { SourceKind } from "./SourceKind.js";

export type JobSpec = { source: InputSource, destination: string, preferred_kind: SourceKind | null, selected_format: string | null, subtitle_languages: Array<string>, overwrite: boolean, };
