// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetalinkFile = { name: string, size: number | null, mirrors: Array<string>, hashes: Array<string>, };
