// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetalinkFile } from "./MetalinkFile.js";

export type MetalinkPreview = { files: Array<MetalinkFile>, total_bytes: number | null, has_insecure_mirrors: boolean, };
