// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineDescriptor } from "./EngineDescriptor.js";
import type { PackDependency } from "./PackDependency.js";
import type { PackFile } from "./PackFile.js";
import type { PackSelfTest } from "./PackSelfTest.js";
import type { TargetId } from "./TargetId.js";
import type { UpstreamComponent } from "./UpstreamComponent.js";

export type PackManifestV1 = { schema_version: number, id: string, version: string, target: TargetId, core_api_min: number, core_api_max: number, security_sequence: number, dependencies: Array<PackDependency>, engines: Array<EngineDescriptor>, components: Array<UpstreamComponent>, files: Array<PackFile>, self_tests: Array<PackSelfTest>, };
