// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackFileRole } from "./PackFileRole.js";

export type PackFile = { path: string, size: number, sha256: string, role: PackFileRole, executable: boolean, };
