// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackSelfTest = { engine_id: string, expected_version: string, timeout_seconds: number, };
