// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackDependency = { pack_id: string, version_req: string, required: boolean, };
