// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackDependency } from "./PackDependency.js";
import type { TargetId } from "./TargetId.js";

export type PackDescriptor = { id: string, version: string, target: TargetId, dependencies: Array<PackDependency>, core_api_min: number, core_api_max: number, security_sequence: number, };
