// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreUpdateInfo } from "./CoreUpdateInfo.js";
import type { CoreUpdateStatus } from "./CoreUpdateStatus.js";

export type PreparedCoreUpdate = { update: CoreUpdateInfo, status: CoreUpdateStatus, };
