// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatOption } from "./FormatOption.js";
import type { SourceKind } from "./SourceKind.js";

export type ResolvedPlan = { source_kind: SourceKind, title: string | null, formats: Array<FormatOption>, subtitles: Array<string>, chapters: number, files: number, warnings: Array<string>, auth_requirements: Array<string>, required_packs: Array<string>, };
