// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceKind } from "./SourceKind.js";

export type RouteDecision = { source_kind: SourceKind, engines: Array<string>, required_packs: Array<string>, };
