// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpAuthorizationInput = { trustAction: string, credentialKind: string, username: string, password: string | null, keyPath: string | null, passphrase: string | null, };
