// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpHostKeyRecord = { host: string, port: number, algorithm: string, raw_key_base64: string, fingerprint_sha256: string, first_seen: string, last_verified: string, revoked: boolean, };
