// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpTrustInfo = { state: string, host: string, port: number, algorithm: string, fingerprintSha256: string, };
