name: Metadata

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  pull-request:
    runs-on: ubuntu-24.04
    env:
      FORBIDDEN_METADATA_REGEX: ${{ vars.FORBIDDEN_METADATA_REGEX }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - name: Validate title and body
        run: node scripts/check-pull-request-metadata.mjs
